[package]
name = "rocket-oauth2-example"
version = "0.1.0"
edition = "2021"


[dependencies]
rocket = "0.5.0"
rocket_dyn_templates = { version = "0.1.0", features = ["handlebars"] }
rocket_oauth2 = "0.5.0"

